ARG IMAGE

FROM ${IMAGE}

ARG BROWSER
ARG NPM_INSTALL

WORKDIR /app

ENV NODE_PATH /app/node_modules

RUN npm install selenium-webdriver lodash assert request ${NPM_INSTALL}

COPY mozlenium-${BROWSER}.js /app/node_modules/mozlenium.js

COPY entrypoint.sh /app

ENTRYPOINT [ "/app/entrypoint.sh" ]
