apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "mozalert-controller.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}

