apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "mozalert-controller.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        {{- include "mozalert-controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        {{- if .Values.secretRef }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretRef }}
        {{- end }}
